version: 1.5.{build}
pull_requests:
  do_not_increment_build_number: true
init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(appveyor_build_version)'
  
before_build:
  - nuget restore
  
build_script:
- cmd: >-
    dotnet restore CoreHelpers.WindowsAzure.Storage.Table\CoreHelpers.WindowsAzure.Storage.Table.csproj
    
    dotnet build -c Release CoreHelpers.WindowsAzure.Storage.Table\CoreHelpers.WindowsAzure.Storage.Table.csproj
    
    msbuild CoreHelpers.WindowsAzure.Storage.Table.Net45\CoreHelpers.WindowsAzure.Storage.Table.Net45.csproj

    nuget pack CoreHelpers.WindowsAzure.Storage.Table.nuspec -Version %APPVEYOR_BUILD_VERSION% -Verbosity detailed
artifacts:
- path: '*.nupkg'
  name: NuGetPackage
