name: CI Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore
      run: dotnet restore CoreHelpers.WindowsAzure.Storage.Table.sln
      env: 
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - name: Build
      run: dotnet build --no-restore -c Release CoreHelpers.WindowsAzure.Storage.Table.sln
      env: 
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - name: Test
      run: dotnet test --no-restore CoreHelpers.WindowsAzure.Storage.Table.sln -e STORAGE="${{ secrets.XUNIT_CONNECTIONSTRING }}"
