name: Publish Release

on:
  release:
    types: ["created"]
    
jobs:
  build-nuget:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Check output
        run: echo ${{ steps.get_version.outputs.RELEASE_VERSION }}
        shell: bash
