name: Publish Release

on:
  release:
    types: ["created"]
    
jobs:
  build-nuget:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Get the release version
        uses: actions/github-script@v5.0.0
        id: get_version
        with: 
          script: |
            const release_tag = context.ref.substring(10)
            const release_version = release_tag.replace('v','')
            core.setOutput('release_tag', release_tag)
            core.setOutput('release_tag', release_version)
            console.log "Release Tag $release_tag"
            console.log "Release Version $release_version"
            console.log context.ref
      - name: Check output
        run: echo "Using release version ${{ steps.get_version.outputs.RELEASE_VERSION }}"
        shell: bash
      - name: Dir
        run: dir ${{ github.workspace }}
      - name: set-version-assemblyinfo
        uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
        with:
          path: '${{ github.workspace }}/CoreHelpers.WindowsAzure.Storage.Table'
          version: ${{ steps.get_version.outputs.RELEASE_VERSION }}
